services:
  suno-service:
    network_mode: host
    ports: !reset []
    networks: !reset []

  speaki-service:
    network_mode: host
    ports: !reset []
    networks: !reset []

  won-confirm-service:
    network_mode: host
    ports: !reset []
    networks: !reset []
